if(NOT DEFINED NUMBER_FILE OR NOT DEFINED OUT)
    message(FATAL_ERROR "bump_build.cmake needs NUMBER_FILE and OUT")
endif()
if(EXISTS "${NUMBER_FILE}")
    file(READ "${NUMBER_FILE}" n)
    string(STRIP "${n}" n)
else()
    set(n 0)
endif()
if(NOT n MATCHES "^[0-9]+$")
    set(n 0)
endif()
math(EXPR n "${n} + 1")
file(WRITE "${NUMBER_FILE}" "${n}\n")
file(WRITE "${OUT}" "#define PM_BUILD ${n}\n")
