#ifndef BATTLE_ACTOR_TYPES_H
#define BATTLE_ACTOR_TYPES_H
/* Generated by the decomp configure step. The first 3DS link does not compile battle code. */
#define ACTOR_LEVEL_NONE 99
#define ACTOR_LEVEL_MAGIKOOPA 0
#endif
